### ISSUE TITLE
Error after compile

### ISSUE THREAD

**Issue by daynnightx** [Co0sh/BetonQuest-Editor#43]
after compiling is finished i get this error

```
javafx.fxml.LoadException: 
file:/C:/Users/Epsilon/Desktop/BetonQuest-Editor-master/target/BetonQuest-Editor.jar!/pl/betoncraft/betonquest/editor/view/tab/ConversationTab.fxml:37
file:/C:/Users/Epsilon/Desktop/BetonQuest-Editor-master/target/BetonQuest-Editor.jar!/pl/betoncraft/betonquest/editor/view/Tabs.fxml:10
file:/C:/Users/Epsilon/Desktop/BetonQuest-Editor-master/target/BetonQuest-Editor.jar!/pl/betoncraft/betonquest/editor/view/Root.fxml:22

	at javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.access$2700(Unknown Source)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(Unknown Source)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.access$2700(Unknown Source)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(Unknown Source)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at pl.betoncraft.betonquest.editor.BetonQuestEditor.start(BetonQuestEditor.java:112)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$$Lambda$53/1968668290.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$45/1915503092.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1026297962.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/1567581361.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$36/1645995473.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Cannot determine type for property.
	at com.sun.javafx.fxml.BeanAdapter.getSetterMethod(Unknown Source)
	at com.sun.javafx.fxml.BeanAdapter.put(Unknown Source)
	at javafx.fxml.FXMLLoader$Element.processEventHandlerAttributes(Unknown Source)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(Unknown Source)
	at javafx.fxml.FXMLLoader.processEndElement(Unknown Source)
	... 30 more

```
i have java 8 and maven

**Comment by Co0sh** [comment]
I was just going to write this:

> Have you tried updating your JDK to latest version?

How did you fix it? 😄
