### ISSUE TITLE
Early Bugs :)

### ISSUE THREAD

**Issue by MWFIAE** [Co0sh/BetonQuest-Editor#8]
Should Bug-Reports be already posted? Or doesn't it make sense, because of early development stage? :) 
If they should be posted, here is something i discovered while trying to load my package ;)

I think the error is (fundamentally) caused by this line:
String lang = parts[2];
QuestPackage.java line 324, it should be:
String lang = parts[3];

java.lang.NullPointerException: Both properties must be specified.
	at com.sun.javafx.binding.BidirectionalBinding.checkParameters(Unknown Source)
	at com.sun.javafx.binding.BidirectionalBinding.bind(Unknown Source)
	at javafx.beans.binding.Bindings.bindBidirectional(Unknown Source)
	at javafx.beans.property.StringProperty.bindBidirectional(Unknown Source)
	at pl.betoncraft.betonquest.editor.controller.ConversationController.displayConversation(ConversationController.java:81)
	at pl.betoncraft.betonquest.editor.controller.ConversationController.setConversations(ConversationController.java:75)
	at pl.betoncraft.betonquest.editor.BetonQuestEditor.display(BetonQuestEditor.java:124)
	at pl.betoncraft.betonquest.editor.controller.MainMenuController.load(MainMenuController.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.control.MenuItem.fire(Unknown Source)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1500(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by MWFIAE** [comment]
Line 269 the same :)

**Comment by Co0sh** [comment]
Yes, you're right, it should be `3`. Thanks ^^  :+1:

**Comment by Co0sh** [comment]
You can post every error you find, it will surely be helpful :3

**Comment by MWFIAE** [comment]
No Problem :) 
Maybe it's better if i start contributing in the github way, cause I also added a few new features :+1: ... but never really worked with it. And for my own Projects im using a private gitlab... 

Also I'm not quite sure if the array index alone will solve the problem, from what i've seen you implemented an algorithmus to determine the most used language and take that as main-language (which is fairly impressive :) ) but this opens this problem again if the main language is not used everywhere. 
Say for example i make german quests, so the main language would be german, but now I download an example package (the_hole), which is only english, so no text is found... But I'm not quite sure what to display instead :/ just some dummy value?

**Comment by Co0sh** [comment]
The language is stored per-package, so you could have all packages in German and download an English package without problems.

In case of a package which is half German half English it will simply choose which language has the most entries. Untranslated fields will have a text "untranslated" or something like this, maybe even a different color. When the user types some string in that text field it will automatically update the language file. That's my idea at least.

Maybe indicating that the field is not translated into a language can be done by making that property empty? I won't have to create a custom observable type that way.

Anyway, that's the problem for the future, I should get modifying and saving data done now.

**Comment by MWFIAE** [comment]
Good point, forgot it was a per package thing :+1: 

Sounds good :) 

A null property throws an error, see stacktrace above... 

I agree, the priorities are clearly modifying and saving.

**Comment by Co0sh** [comment]
I'm planning to sell binaries of this editor once it's finished. I'd like to make it a kind of BetonQuest donation - people who can afford it would buy it and everyone else could compile a copy from source (it's GPLv3 after all).

If you're all right with that, I'm happy to accept your contributions :D

**Comment by MWFIAE** [comment]
I know, you mentioned on the issue on BetonQuest itself regarding the editor :) 
(I'm the guy with the half finished c# version, if you don't remember me. )

As long as it's usable by anybody who is willing to invest some effort in it I'm fine with it :)

**Comment by Co0sh** [comment]
I know, I just wanted to make it clear ^^

By the way, I just fixed another problem with loading translations, the `if` condition was inverted and it was causing NPE.

**Comment by MWFIAE** [comment]
Already took it over :) 
I fixed one problem and added one new feature :stuck_out_tongue_winking_eye:

**Comment by Co0sh** [comment]
What's this feature? :smile:

**Comment by MWFIAE** [comment]
That you can actually select a conversation option and see its values :) 
(6 lines, very impressive^^ )

**Comment by Co0sh** [comment]
I've already got this on my local repo :no_mouth:  Wait a sec, I'll push it, just need to separate it from the saving stuff I'm doing right now.

**Comment by MWFIAE** [comment]
local changes are bad changes ;)

**Comment by MWFIAE** [comment]
I saw that you made a change with "onMouseClicked="#clickPlayerOption"" is there any advantage over just using something like this? Or is it just personal preference? 
(Just asking out of curiosity, cause I started with javafx just today ) 

		//Update displayed option if user selects one
		playerList.getSelectionModel().selectedItemProperty().addListener(
				(observable, oldValue, newValue) -> displayOption(newValue)
		);

**Comment by Co0sh** [comment]
I think it has the same effect, although I'm not 100% sure, there may be some differences. In this case both approaches should be fine.

I prefer to set event handlers via fxml if possible though ^^

**Comment by MWFIAE** [comment]
I thought this approach may be better, because it should handle everything (like selecting the item with the keyboard or something. ) whereas yours should only handle mouseinput. I may be wrong, but the naming is clear :) 
But I also think a fxml change would be clearer...

**Comment by Co0sh** [comment]
You may be right, keyboard won't be detected that way. Adding `onKeyReleased` with the same handler method will solve that though.
