### ISSUE TITLE
Incorrect return type

### ISSUE THREAD

**Issue by Co0sh** [Co0sh/BetonQuest-Editor#9]
There's quite a strange error when calling `getObjectFromComboBox` method in `ConversationController` class. When running the program in Eclipse, everything works fine, expected `T` type is returned. But when it's compiled with Maven, this method always returns a `String`. @MWFIAE, can you confirm that? Maybe it's only something in my JDK/JRE (although I'm running latest versions of both).

    Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
            at javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
            at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
            at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
            at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
            at javafx.event.Event.fireEvent(Unknown Source)
            at javafx.scene.Node.fireEvent(Unknown Source)
            at javafx.scene.control.Button.fire(Unknown Source)
            at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
            at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
            at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
            at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
            at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
            at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
            at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
            at javafx.event.Event.fireEvent(Unknown Source)
            at javafx.scene.Scene$MouseHandler.process(Unknown Source)
            at javafx.scene.Scene$MouseHandler.access$1500(Unknown Source)
            at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
            at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
            at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
            at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
            at java.security.AccessController.doPrivileged(Native Method)
            at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(Unknown Source)
            at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
            at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
            at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
            at com.sun.glass.ui.View.notifyMouse(Unknown Source)
            at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
            at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
            at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at sun.reflect.misc.Trampoline.invoke(Unknown Source)
            at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
            ... 61 more
    Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to pl.betoncraft.betonquest.editor.model.NpcOption
            at pl.betoncraft.betonquest.editor.controller.ConversationController.addStartingOption(ConversationController.java:242)
        ... 70 more

Simplest solution would be to copy-paste that code into all method calling `getObjectFromComboBox`, so generics are not used in this case. That's not the point though...

**Comment by MWFIAE** [comment]
Not sure if it's exactly the same error (I'm not getting any error messages), but it can't load the package if I start the maven build... 
(Is it possible to directly start with maven, not only build? Because maybe then I could get a error message :) )

**Comment by Co0sh** [comment]
And did you pull my latest commit? The YAML parser dependency wasn't included in the final package before, that's why it can't load anything.

**Comment by Co0sh** [comment]
I don't think Maven can actually run what it's building.

**Comment by MWFIAE** [comment]
Yeah i just merged it :+1: 
(saw it right after posting)

But same as before, didn't load a thing....

**Comment by Co0sh** [comment]
Not good... Try running it from the command line, it will display error then ^^

**Comment by MWFIAE** [comment]
oh i think it was my bad, let me test something....

**Comment by MWFIAE** [comment]
Yes it was me... I had the project 2 times in eclipse (one of my privat gitlab, one of the github fork) and I was compiling the wrong outdated one :/ 
Now it loads :+1:

**Comment by Co0sh** [comment]
Great :grinning: Try to add a starting option in the conversation to trigger that error.

**Comment by Co0sh** [comment]
By the way, I found out that the `combo.getValue()` returns a `String`, so I think it's safe to assume the method is getting `ComboBox<String>` as an argument, instead of i.e. `ComboBox<NpcOption>`.

**Comment by MWFIAE** [comment]
I'm also getting it for the CurrentConversation Combobox, so we can assume its a problem with every ComboBox :-1:

**Comment by Co0sh** [comment]
Wow, I didn't expect that:

	@FXML private void addStartingOption() {
		System.out.println("test...");
		System.out.println(startingOptionsCombo.getValue().getClass());
		System.out.println("...end");
		NpcOption option = getObjectFromComboBox(startingOptionsCombo, e -> currentConversation.newNpcOption(e));
		if (option != null && !startingOptionsChoice.getItems().contains(option)) {
			startingOptionsChoice.getItems().add(option);
			BetonQuestEditor.refresh();
			displayOption(option);
		}
	}

It displays `test...` and then there's an error. It works when I don't call `getClass()`. It's like it was casting the returned `String` to `NpcOption` then. Looks like a complier bug?

**Comment by MWFIAE** [comment]
Yeah it does.... 
Would never thought to say something like that, but... awesome, this is something I always wanted to find :grin:

**Comment by Co0sh** [comment]
It's our bug :laughing:  http://stackoverflow.com/questions/38058801/bug-with-javafx-combobox
No answers though...

**Comment by Co0sh** [comment]
And then there's [this](http://stackoverflow.com/questions/30091401/javafx-combobox-selected-item-type-changes-when-not-focused), he says the ComboBox needs focus. Adding `startingOptionsCombo.requestFocus();` does not make it work though.

**Comment by Co0sh** [comment]
Making the ComboBox not editable in FXML fixes this problem, but that way users cannot add new events/conditions/options directly with that window. For now it will work, but in the future I will make these controls as TextFields with autocomplete feature :unamused:

**Comment by MWFIAE** [comment]
okay.... but autocomplete also doesn't sound bad :+1: 

disgusting little java... That's why I'm sticking with C# :stuck_out_tongue_winking_eye: (unless java is needed like for bukkit plugins)

**Comment by Jack-McKalling** [comment]
Don't blame Java, you're over generalizing a JavaFX issue :D Nothing wrong with Java.
^almost a rant haha.

**Comment by Co0sh** [comment]
Actually there's something wrong with Java if it allows for dynamic type change from `ComboBox<NpcOption>` to `ComboBox<String>`. I can't see how it's possible for JavaFx to achieve such bug, it must be messing with internal Java code, under the API or something like that. I don't know Java internals well enough to tell the cause.

**Comment by Jack-McKalling** [comment]
Java does not allow that, that's a violation of the type safety rule. I suspect ComboBox to have a bug in its type declarations somewhere, to cause this. The fact an error comes up shows Java doesn't like this behavior.

**Comment by Co0sh** [comment]
I just wonder how did they do that :P

**Comment by Jack-McKalling** [comment]
I'll look into the code and see if I can spot anything somewhere :smiley:

**Comment by Co0sh** [comment]
Alright. I need to start packing for the Woodstock festival now, I'll be back on Monday. I was hoping I could make this editor at least "working" before leaving, but this bug slowed me down.

When running from Eclipse it works just fine, it's possible to edit everything in a single package except for  _main.yml_ file. I'll finish this when I'm back We'll call it `v0.1` and focus on some nice features like keyboard support, cross-conversation pointers, highlighting errors, translations etc.

**Comment by MWFIAE** [comment]
And don't forget some nice to have quickedit features ;) 
Something that was first prio in my own editor... Cause you want to make it as easy as possible for the users :) 
For example one thing I made was that you could add "Tags" which autogenerated the corresponding events and condition. And some kind of quick linking between conversation nodes :)

**Comment by Co0sh** [comment]
I'm planning to add it as "Insert" in the menu bar. Maybe even an API to make such quick edits unified?

**Comment by Jack-McKalling** [comment]
I've researched into the JavaFX source code for the ComboBox, and it appears there is or has been (depending on the version you're using) a bug with the focus property inside the ComboBoxBase class, which ComboBox is extending. They tried to fix it, and said fix refers to RT-29885, whatever that means. [Source](http://hg.openjdk.java.net/openjfx/8/master/rt/rev/3db94ad212b6)

Judging from the code, I'm assuming the focus isn't/wasn't correctly working when the value of the textfield of the ComboBox is stored into the ComboBox, and they changed it to set the focus manually. I'm not sure if this is related to the issue you're having here, or if the fix actually works. But this might explain why requesting focus didn't help.

I think it's safer to use a non-editable combobox for selecting existing items, and a separate textfield for adding new ones. The editable combobox seems to have had multiple issues before.

**Comment by Co0sh** [comment]
So it looks like they won't be fixing this anytime soon.

There's no enough room to add yet another TextField, I'll simply replace the ComboBox with an autocompletable TextField.

**Comment by Jack-McKalling** [comment]
An autocomplete feature does offer the advantage that it can contain a lot more items, because you won't need to scroll through them all like with a combobox.

**Comment by Co0sh** [comment]
Exactly ^^

**Comment by MWFIAE** [comment]
Space and displaying all items was always a problem, especially with very komplex conversations. I tried to solve it myself with wrappanels and buttons (and an own window for every "object"-type like objectives, events, conditions etc. ) to have an overview over all things...

It was also one of the first things when I saw you gui, I was like: omg, how should that work with my main quest giver :grin: But then I thought in an extra step one could add more popup like windows to select such stuff, so no hurry for now :)

**Comment by Co0sh** [comment]
Well, I won't insist on keeping the conversation view like this if it's inconvenient. We can change it later, no problem ^^

**Comment by MWFIAE** [comment]
I think things like events and conditions are not really to be displayed in a combobox, and another listview in this view would probably be to much :sweat_smile: 
So how did I solve it? (and yes I admit, I'm opening to much windows, had 6 open, till i get to this point^^ ) 
![image](https://cloud.githubusercontent.com/assets/6072971/16769436/f7ed0d12-4848-11e6-9b8a-2ad0364246b7.png)
If editing a conversation option, I show all the events in a Textbox (just like it would be if changing the file directly), but I have a Button to actually open an events window, where i can just click to select/deselect an event for this option. Easy visualisation through colors.  (Extra Points for also enabling adding and deleting events in there :+1:  ) The same goes for conditions, but with 3 States (off, on, negated) 

You don't have to make it like this, but it was the best that I could think of :D :) (and it doesn't require 3 clicks for every single event I want to add ) 

PS: we are really going offtopic... :smile:

**Comment by MWFIAE** [comment]
Also now the return type is incorrect with eclipse compiling. (At least for me)

**Comment by Co0sh** [comment]
Pop-up window for events/conditions is a good idea, I'll implement that after making it work. Also I forgot about negated conditions... Thank you for reminding me of that.

**Comment by Co0sh** [comment]
It might be better to implement choosing these things only via pop-up window. That way I can display a `ListView` and control buttons outside of the conversation flow. It will be easy to reorder things displayed that way, and in case of conditions I can add a `CheckBox` to allow inverting them (I will have to wrap `Condition` class it can be negated without making copies of it).

**Comment by MWFIAE** [comment]
Ok just that I understood everything correctly and give my opinion to everything :grinning:  : 
Listview with buttons to "sort" the conversation options? Sounds good :+1: 
Conditions with checkboxes? To be honest that just doesn't sound right to me, I don't like clicking on tiny checkboxes :grinning: But I can understand, that it would make the whole thing easier. So maybe I can accept it for now :stuck_out_tongue_winking_eye: 
Wrap Conditions? Yeah, would propably be the cleanest way of doing things :+1:

**Comment by Co0sh** [comment]
I can add a keyboard shortcut for inverting selected conditions :smile:

**Comment by MWFIAE** [comment]
oh yeah shortcuts! :grin: 
Always forgetting about them, cause I really hate to implement them (don't ask, childhood trauma like thing :laughing: )

**Comment by Co0sh** [comment]
Alright, I'm closing this one since the bug is "fixed".
